spring:
  application:
    name: weshopify-notifications-service

server:
  port: 5023
  
sendgrid: 
 api: 
   key: <use your sendgrid account key>
   verifyEmail: http://${USER_SERVICE_HOST:localhost}:${USERS_SERVICE_PORT:5014}/users/verifyUser/
   from: weshopifyapp@yopmail.com
